### ISSUE TITLE
Is selenium Framework for Swift ?

### ISSUE THREAD

**Issue by SheethalJossan** [appium/selenium-objective-c#76]
While using **" pod 'Selenium' "** we are getting Objective C Selenium Framework. So we need to bridge to use it. 
Please give a reply.

**Comment by JamieEdge** [comment]
You should be able to use this framework with Swift by adding the below line to your [bridging header](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html).

```
#import <Selenium/Selenium.h>
```

**Comment by SheethalJossan** [comment]
Thank you so much. While using bridgingHeader, it's working fine. 

_import Selenium_

**Comment by rkavalap** [comment]
@triager please close
